title: Team TJA2
description: Traffic Jam Assist Project Website
url: "https://www.egr.msu.edu"
baseurl: "/cse435/tja2"
permalink: /:path/


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  team_members:
    output: true
  meeting_agendas:
    output: true

# Exclude from processing
exclude:
  - app.py
  - Dockerfile
  - docker-compose.yml
  - requirements.txt
  - __pycache__

include:
  - Unity