title: Team TJA2
description: Traffic Jam Assist Project Website
baseurl: "/CSE435-Group-Website"
url: "https://fiorittoev.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  team_members:
    output: true
  meeting_agendas:
    output: true

# Exclude from processing
exclude:
  - app.py
  - Dockerfile
  - docker-compose.yml
  - requirements.txt
  - __pycache__